[package]
name = "nu_plugin_from_hdf5"
version = "0.1.0"
edition = "2021"

[dependencies]
nu-plugin = "0.76"
nu-protocol = { version = "0.76", features = ["plugin"] }
hdf5 = "0.8"
hdf5-sys = "0.8"

[profile.release]
lto = true
codegen-units = 1

[patch.crates-io]
hdf5 = { git = "https://github.com/Berrysoft/hdf5-rust.git", branch = "fix/mingw" }
hdf5-sys = { git = "https://github.com/Berrysoft/hdf5-rust.git", branch = "fix/mingw" }
